# GolangCI-Lint configuration
# See https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # Enabled by default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    
    # Additional linters
    - bodyclose
    - contextcheck
    - cyclop
    - dupl
    - durationcheck
    - errname
    - errorlint
    - copyloopvar
    - forcetypeassert
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nolintlint
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - usetesting
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace

  disable:
    - exhaustive
    - forbidigo
    - funlen
    - gochecknoglobals
    - godox
    - err113  # renamed from goerr113
    - gomoddirectives
    - nlreturn
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  cyclop:
    max-complexity: 15
    package-average: 10.0
    skip-tests: true

  dupl:
    threshold: 100

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104 # Audit errors not checked
      - G204 # Subprocess launched with variable

  goconst:
    min-len: 2
    min-occurrences: 3
    ignore-tests: true

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/yairfalse/wgo

  lll:
    line-length: 120
    tab-width: 4

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  nestif:
    min-complexity: 4

  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: false

  revive:
    rules:
      - name: exported
        arguments: ["checkPrivateReceivers"]
      - name: package-comments
      - name: var-naming
      - name: range-val-in-closure
      - name: range-val-address
      - name: waitgroup-by-value
      - name: atomic
      - name: call-to-gc
      - name: duplicated-imports
      - name: import-shadowing
      - name: struct-tag
      - name: modifies-parameter
      - name: unreachable-code

  unparam:
    check-exported: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
        - unparam
        - gocritic

    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"

    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "

    # Exclude some govet issues
    - linters:
        - govet
      text: "declaration of.*shadows declaration at"

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

  fix: false