# GoReleaser configuration for VAINO
# This handles multi-platform builds and package manager distributions
# The Finnish creator god's divine release pipeline

project_name: vaino

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: vaino
    main: ./cmd/vaino
    binary: vaino
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w 
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildTime={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - docs/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

# Homebrew Formula - Divine Blessing for macOS
brews:
  - name: vaino
    tap:
      owner: yairfalse
      name: homebrew-vaino
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    
    homepage: "https://github.com/yairfalse/vaino"
    description: "Ancient Finnish wisdom for modern infrastructure"
    license: "MIT"
    
    dependencies:
      - name: git
        type: optional
    
    install: |
      bin.install "vaino"
      bash_completion.install "completions/vaino.bash" => "vaino"
      zsh_completion.install "completions/vaino.zsh" => "_vaino"
      fish_completion.install "completions/vaino.fish"
    
    test: |
      system "#{bin}/vaino", "version"

# Scoop Manifest - Windows Blessing
scoops:
  - repository:
      owner: yairfalse
      name: scoop-vaino
      branch: main
      token: "{{ .Env.SCOOP_GITHUB_TOKEN }}"
    
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
    
    homepage: "https://github.com/yairfalse/vaino"
    description: "Ancient Finnish wisdom for modern infrastructure"
    license: MIT

# Linux Packages - Divine Distribution
nfpms:
  - id: packages
    package_name: vaino
    vendor: VAINO Contributors
    homepage: https://github.com/yairfalse/vaino
    maintainer: Yair <yair@example.com>
    description: |-
      Ancient Finnish wisdom for modern infrastructure.
      VAINO is the Finnish creator god for infrastructure monitoring.
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    
    dependencies:
      - git
    
    recommends:
      - terraform
      - aws-cli
    
    contents:
      - src: ./completions/vaino.bash
        dst: /usr/share/bash-completion/completions/vaino
        file_info:
          mode: 0644
      
      - src: ./completions/vaino.zsh
        dst: /usr/share/zsh/site-functions/_vaino
        file_info:
          mode: 0644
      
      - src: ./completions/vaino.fish
        dst: /usr/share/fish/vendor_completions.d/vaino.fish
        file_info:
          mode: 0644
      
      - src: ./README.md
        dst: /usr/share/doc/vaino/README.md
        file_info:
          mode: 0644
      
      - src: ./LICENSE
        dst: /usr/share/doc/vaino/LICENSE
        file_info:
          mode: 0644
    
    scripts:
      postinstall: |
        #!/bin/bash
        echo "VAINO installed successfully!"
        echo "Run 'vaino version' to verify installation"
      
      postremove: |
        #!/bin/bash
        echo "VAINO has been removed"

# Snapcraft - Divine Ubuntu Distribution
snapcrafts:
  - name: vaino
    summary: Ancient Finnish wisdom for modern infrastructure
    description: |
      VAINO is the Finnish creator god for infrastructure monitoring.
      Ancient wisdom meets modern technology to watch over your cloud kingdom.
    
    grade: stable
    confinement: strict
    base: core20
    
    license: MIT
    
    apps:
      vaino:
        command: vaino
        plugs:
          - home
          - network
          - personal-files

# Docker Images - Containerized Finnish Power
dockers:
  - image_templates:
      - "yairfalse/vaino:{{ .Tag }}-amd64"
      - "yairfalse/vaino:latest-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    dockerfile: Dockerfile
    
  - image_templates:
      - "yairfalse/vaino:{{ .Tag }}-arm64"
      - "yairfalse/vaino:latest-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
    dockerfile: Dockerfile

# Docker Manifests for multi-arch - Unified Finnish Distribution
docker_manifests:
  - name_template: "yairfalse/vaino:{{ .Tag }}"
    image_templates:
      - "yairfalse/vaino:{{ .Tag }}-amd64"
      - "yairfalse/vaino:{{ .Tag }}-arm64"
  
  - name_template: "yairfalse/vaino:latest"
    image_templates:
      - "yairfalse/vaino:latest-amd64"
      - "yairfalse/vaino:latest-arm64"

# GitHub Release - Divine Distribution
release:
  github:
    owner: yairfalse
    name: vaino
  
  name_template: "v{{.Version}}"
  
  header: |
    ## VAINO v{{.Version}} Release Notes
    
    Ancient Finnish wisdom for modern infrastructure - Väinämoinen's divine creation
    
  footer: |
    ## Installation
    
    ### macOS/Linux
    ```bash
    brew install yairfalse/vaino/vaino
    ```
    
    ### Ubuntu/Debian
    ```bash
    curl -L https://github.com/yairfalse/vaino/releases/download/v{{.Version}}/vaino_{{.Version}}_linux_amd64.deb -o vaino.deb
    sudo dpkg -i vaino.deb
    ```
    
    ### Universal Script
    ```bash
    curl -sSL https://install.vaino.sh | bash
    ```
    
    **Full Documentation**: https://github.com/yairfalse/vaino

# Announce releases - Spread the Finnish Gospel
announce:
  twitter:
    enabled: true
    message_template: |
      VAINO {{.Tag}} is out! 🇫🇮⚡
      
      Ancient Finnish wisdom for modern infrastructure - Väinämoinen watches over your cloud!
      
      https://github.com/yairfalse/vaino/releases/tag/{{.Tag}}
      
      #vaino #finnish #infrastructure #devops #cloud #mythology