name: CI Test

on:
  push:
    branches: [ feature/correlation-engine-parallelization ]

env:
  GO_VERSION: '1.23'

jobs:
  test:
    name: Simple Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        skip-cache: true
    
    - name: Basic test
      run: |
        echo "Go version:"
        go version
        echo "Building..."
        go build -o wgo ./cmd/wgo
        echo "Testing build..."
        ./wgo --help
        echo "✅ Success!"