name: Release

on:
  push:
    tags:
      - 'v*'

env:
  GO_VERSION: '1.23'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Build binaries
      run: |
        # Linux
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o ./dist/wgo-linux-amd64 ./cmd/wgo
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o ./dist/wgo-linux-arm64 ./cmd/wgo
        
        # macOS
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o ./dist/wgo-darwin-amd64 ./cmd/wgo
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o ./dist/wgo-darwin-arm64 ./cmd/wgo
        
        # Windows
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o ./dist/wgo-windows-amd64.exe ./cmd/wgo
    
    - name: Create checksums
      run: |
        cd dist
        sha256sum * > checksums.txt
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        draft: false
        prerelease: false
        generate_release_notes: true